user: root

##--  Compose  --##

app_name: jenkins
app_container_name: "{{ app_name }}"
app_version: "{{ jenkins_version }}"
app_host_port: 9000
app_container_port: 8080
app_homedir: "/opt/{{ app_container_name }}-home"


compose:
  mainapp:
    name: "{{ app_name }}"
    container_name: "{{ app_container_name }}"
    container_hostname: "{{ app_container_name }}" 
   
    host_port: "{{ app_host_port }}"
    container_port: "{{ app_host_port }}"
    extra_hosts:
      - "extra-host1:{{ address['extra-host1'] }}"
      - "extra-host2:{{ address['extra-host2'] }}"

    image: "{{ docker_username }}/{{ app_name }}:{{ app_version }}"

    home_dir: "{{ app_homedir }}"
    home_dir_exists: true
    home_dir_backup: true

    ports: 
      - "127.0.0.1:{{ app_host_port }}:{{ app_container_port }}"
      - "{{ ip_address }}:{{ app_host_port }}:{{ app_container_port }}"

    volumes:
      - "{{ app_homedir }}:/var/jenkins_home:z"
    links:
    environments:
    entrypoint:
    command:


